language: objective-c
osx_image: xcode11.6
cache:
  - bundler
  - cocoapods
xcode_project: Pikalong.xcworkspace
xcode_scheme: Pikalong
xcode_destination: platform=iOS Simulator, OS=12.1, name=iPhone X
before_install:
    - bundle install
    - gem install linterbot
    - bundle exec pod install --repo-update
install:
    - set -o pipefail
    - sudo systemsetup -settimezone Asia/Ho_Chi_Minh
    - bundle install --path=vendor/bundle --jobs 4 --retry 3
before_script:
  - chmod a+x ./scripts/lint
script:
    - ./scripts/lint
    - bundle exec fastlane test
    - bundle exec fastlane deploy_dev
